/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package IntegrationTests;

import org.junit.Test;
import org.opencv.videoio.VideoCapture;


public class IntegrationTest {
    @Test
    public void testMirrorImage() {
        VideoCapture c = new VideoCapture();

    }
}
