/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package IntegrationTests;

import java.io.IOException;
import java.util.Arrays;

public class CLI {
    private String commandBase;

    public CLI(String location) {
        commandBase = location + Gradle.gradle();
    }

    public void execute(String[] args) {
        String[] cmdargs = new String[args.length + 1];
        cmdargs[0] = commandBase;
        System.arraycopy(args, 0, cmdargs, 1, args.length);
        try {
            Runtime.getRuntime().exec(cmdargs);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
